// Complete Modle Reset Workflow - Backup, Reset, Verify
require('dotenv').config();
const { backupModleData } = require('./backup_modle_data');
const resetAllModleData = require('./reset_modle_system');
const mongoose = require('mongoose');
const User = require('../models/User');

async function completeModleReset() {
  try {
    console.log('🚀 COMPLETE MODLE RESET WORKFLOW\n');
    console.log('This will perform the following steps:');
    console.log('1. 💾 Create backup of current data');
    console.log('2. 🔄 Reset all user Modle data'); 
    console.log('3. ✅ Verify reset completion');
    console.log('4. 📊 Generate reset summary\n');

    // Step 1: Create backup
    console.log('📋 STEP 1: Creating backup...');
    const backupFile = await backupModleData();
    if (!backupFile) {
      console.log('⚠️  No data to backup. Proceeding with reset anyway...');
    } else {
      console.log(`✅ Backup completed: ${backupFile}\n`);
    }

    // Step 2: Perform reset
    console.log('📋 STEP 2: Performing system reset...');
    await resetAllModleData();
    console.log('✅ Reset completed\n');

    // Step 3: Verify reset
    console.log('📋 STEP 3: Verifying reset completion...');
    await verifyReset();

    // Step 4: Generate summary
    console.log('📋 STEP 4: Generating final summary...');
    await generateResetSummary(backupFile);

    console.log('\n🎉 COMPLETE MODLE RESET WORKFLOW FINISHED!');
    console.log('✅ All users now have a fresh start');
    console.log('🎮 Ready for new Modle adventures');

  } catch (error) {
    console.error('❌ Reset workflow failed:', error);
    process.exit(1);
  }
}

async function verifyReset() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    
    const users = await User.find({ modle: { $exists: true } });
    let allReset = true;
    let issueCount = 0;

    for (const user of users) {
      if (user.modle) {
        const languages = ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', '_global'];
        
        for (const lang of languages) {
          const modleData = user.modle.get ? user.modle.get(lang) : user.modle[lang];
          if (modleData) {
            const streak = modleData.streak || 0;
            const historyCount = modleData.history ? Object.keys(modleData.history).length : 0;
            const lastPlayed = modleData.lastPlayed;

            if (streak !== 0 || historyCount !== 0 || lastPlayed !== null) {
              console.log(`⚠️  User ${user.username} - ${lang}: streak=${streak}, history=${historyCount}, lastPlayed=${lastPlayed}`);
              allReset = false;
              issueCount++;
            }
          }
        }
      }
    }

    if (allReset) {
      console.log('✅ Verification passed - All data successfully reset');
    } else {
      console.log(`⚠️  Verification found ${issueCount} issues - some data may not be fully reset`);
    }

    await mongoose.disconnect();
    return allReset;

  } catch (error) {
    console.error('❌ Verification failed:', error);
    return false;
  }
}

async function generateResetSummary(backupFile) {
  const timestamp = new Date().toISOString();
  const today = new Date().toISOString().slice(0, 10);

  const summary = `
# Modle System Reset Summary

**Reset Date:** ${today}  
**Reset Time:** ${timestamp}  
**Backup File:** ${backupFile || 'No backup created'}

## What Was Reset

✅ **All User Streaks:** Reset to 0 across all languages  
✅ **All Play History:** Cleared completely  
✅ **All Last Played Dates:** Set to null  
✅ **Global Streaks:** Reset to 0 for all users  

## Languages Affected

- English
- Hindi  
- Tamil
- Telugu
- Kannada
- Malayalam
- Global (cross-language) streaks

## User Impact

🎮 **Fresh Start:** All users can begin building streaks from today  
🌍 **Global Streak System:** Ready for cross-language gameplay  
📱 **Daily Reset UI:** Will show clean state for all users  
🔄 **Fair Gameplay:** Everyone starts from the same point  

## Technical Details

- Database: All user.modle fields reset to fresh state
- Backup: ${backupFile ? 'Created successfully' : 'No backup needed'}
- Verification: ${await verifyReset() ? 'Passed' : 'Issues detected'}
- Reset Method: Complete system reset script

## Next Steps for Users

1. 🎯 Choose any language to play today
2. 🔥 Start building new streaks  
3. 🌍 Enjoy cross-language streak system
4. 📱 Experience daily UI reset

## For Administrators

- Monitor user engagement post-reset
- Check for any issues with new streak calculations
- Verify global streak system is working
- Backup file available for reference: ${backupFile || 'N/A'}

---
*Generated by Modle Reset Workflow Script*  
*Time: ${timestamp}*
`;

  try {
    const fs = require('fs').promises;
    const path = require('path');
    
    const summaryDir = path.join(__dirname, 'backups');
    const summaryFile = path.join(summaryDir, `reset_summary_${today}.md`);
    
    await fs.writeFile(summaryFile, summary, 'utf8');
    console.log(`📄 Reset summary saved to: ${summaryFile}`);
    
  } catch (error) {
    console.error('⚠️  Could not save summary file:', error.message);
    console.log('\n📄 RESET SUMMARY:');
    console.log(summary);
  }
}

// Interactive confirmation for safety
function confirmWorkflow() {
  const readline = require('readline');
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise((resolve) => {
    console.log('🚨 COMPLETE MODLE SYSTEM RESET WORKFLOW 🚨');
    console.log('This will:');
    console.log('1. Backup all current Modle data');
    console.log('2. Reset ALL users to fresh start');
    console.log('3. Verify the reset worked');
    console.log('4. Generate documentation');
    console.log('\nThis action affects all users and cannot be easily undone!');
    
    rl.question('\nType "CONFIRM COMPLETE RESET" to proceed: ', (answer) => {
      rl.close();
      resolve(answer === 'CONFIRM COMPLETE RESET');
    });
  });
}

// Main execution
async function main() {
  try {
    const forceReset = process.argv.includes('--force');
    
    if (!forceReset) {
      const confirmed = await confirmWorkflow();
      if (!confirmed) {
        console.log('\n❌ Reset workflow cancelled. No data was modified.');
        process.exit(0);
      }
    } else {
      console.log('🚀 Force mode enabled - skipping confirmation');
    }

    await completeModleReset();

  } catch (error) {
    console.error('💥 Workflow execution failed:', error);
    process.exit(1);
  }
}

// Check if script is run directly
if (require.main === module) {
  console.log('🚀 Complete Modle Reset Workflow Starting...');
  main();
} else {
  module.exports = { completeModleReset, verifyReset };
}

// Usage:
// node complete_modle_reset.js              (interactive with confirmation)
// node complete_modle_reset.js --force      (skip confirmation)